name: Release App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Electron App
        run: npm run dist

      - name: Compress Build Output (Zip)
        run: |
          Compress-Archive -Path dist/Daerong-win32-x64 -DestinationPath dist/Daerong-win32-x64.zip
        shell: powershell

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Daerong-win32-x64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
